CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SCHEMA caes AUTHORIZATION postgres;
-- Produção: CREATE SCHEMA caes AUTHORIZATION gysjfhgdnklwum;

CREATE TABLE caes.menu
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    uuid character varying(37) NOT NULL,
    label character varying(20) NOT NULL,
    link character varying(20) NOT NULL,
    CONSTRAINT pk_menu_id PRIMARY KEY (id)
);

CREATE TABLE caes.raca
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    uuid character varying(37) NOT NULL,
    nome character varying(20) NOT NULL,
    CONSTRAINT pk_raca_id PRIMARY KEY (id)
);

CREATE TABLE caes.donos
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    uuid character varying(37) NOT NULL,
    nome character varying(20) NOT NULL,
    ddd character varying(2) NOT NULL,
    telefone character varying(9) NOT NULL,
    CONSTRAINT pk_dono_id PRIMARY KEY (id)
);

CREATE TABLE caes.caes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    uuid character varying(37) NOT NULL,
    nome character varying(20) NOT NULL,
    sobrenome character varying(20),
    nascimento timestamp with time zone NOT NULL DEFAULT now(),
    sexo character(1) DEFAULT 'M',
    datavenda timestamp with time zone,
    valor numeric(12, 2),
    racaid integer NOT NULL,
    descricao character varying(255),
    paiId integer,
    maeId integer,
    CONSTRAINT pk_caes_id PRIMARY KEY (id),
    CONSTRAINT fk_pai_id FOREIGN KEY (paiId)
        REFERENCES caes.caes (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT fk_mae_id FOREIGN KEY (maeId)
        REFERENCES caes.caes (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT fk_raca_id FOREIGN KEY (racaid)
        REFERENCES caes.raca (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);

CREATE TABLE caes.donoscaes
(
    donoid integer NOT NULL,
    caoid integer NOT NULL,
    CONSTRAINT donoidcaoid PRIMARY KEY (donoid, caoid),
    CONSTRAINT donoiddonos FOREIGN KEY (donoid)
        REFERENCES caes.donos (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT caoidcaes FOREIGN KEY (caoid)
        REFERENCES caes.caes (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);
